# Generated by Django 4.0.6 on 2022-11-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyPole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='many_test')),
            ],
        ),
        migrations.CreateModel(
            name='ManyToManyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole', models.CharField(choices=[('ДА', 'ДА'), ('НЕТ', 'НЕТ')], max_length=3, verbose_name='Вопрос')),
                ('photo', models.ManyToManyField(related_name='many_pole', to='note.manypole')),
            ],
        ),
    ]
