# Generated by Django 4.1 on 2022-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_manypole_photo_remove_manytomanytest_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manypole',
            name='photo',
            field=models.ImageField(null=True, upload_to='many_test'),
        ),
    ]
