# Generated by Django 4.0.6 on 2022-11-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_alter_manypole_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manytomanytest',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='manytomanytest',
            name='user',
        ),
        migrations.DeleteModel(
            name='ManyPole',
        ),
        migrations.DeleteModel(
            name='ManyToManyTest',
        ),
    ]
